const express = require ('express');
const http = require('http');
const path = require('path');
const cors = require('cors');
const fs = require('fs');
const multer = require('multer');

const app = express (); // making an express application
const server = http.createServer(app);

const PORT = process.env.PORT || 5000;

app.use(cors()); // Suppress CORS warning.

app.use(express.static(path.join(__dirname, 'public')));
app.get ('/', (req, res) => res.sendFile(__dirname + './public/fish.html'))
//app.get('/mouse', (req, res) => res.setFile(__dirname+'/public/mouse.html'))

const audioPath = path.join(__dirname, 'nicknameToResults');
const uploadAudio = multer({dest: audioPath});
const uploadAudioDetail = uploadAudio.fields([{name: 'nickname'}, {name: 'audio'}]);

app.post('/upload-audio', uploadAudioDetail, (req, res) => {
    const nickname = req.body.nickname;
    const audio = req.files['audio'][0];

    // Rename the file since its name is automatically generated by multer.
    fs.renameSync(path.join(audioPath, audio.filename), path.join(audioPath, `${nickname}.mp3`));
    console.log(`Saved ${nickname}.mp3!`);
});

server.listen(PORT, function(){
    console.log(`initiating server at ${ PORT }`);
})
